### ISSUE TITLE
setFont: infinite loop

### ISSUE THREAD

**Issue by federicocappelli** [matteogobbi/MGTextView#1]
Env: iPhone, iOS 8.2, Auto layout with size classes
MGTextView used in a UITableViewCell Initialised in storyboard.

Infinite loop from:

```
- (BOOL)mg_adjustContentSize
{
    if (!self.font) {
        self.font = DEFAULT_FONT;
        return NO;
    } 
... 
    return YES;
}
```

The self.font = DEFAULT_FONT; calls the overwritten setFont: method:

```
- (void)setFont:(UIFont *)font
{
    if ([self.font isEqual:font]) {
        return;
    }
    [super setFont:font];

    [self mg_adjustContentSize];
}
```

**Comment by matteogobbi** [comment]
Is not a loop ;) check better!

This code is wanted. 

After the first time, this branch will be not longer executed:

``` objc
if (!self.font) {
    self.font = DEFAULT_FONT;
    return NO;
} 
```

**Comment by federicocappelli** [comment]
wasn't an empiric observation, a my test code crashes at [super setFont:font]; I'm trying to replicate the bug for you.

**Comment by matteogobbi** [comment]
No live crashes here. And also: `[super setFont:font]` is executed on super. So it is not related at all with the code in this class. If it is crashed just once for you, maybe the error was another, otherwise it should continuing to crash now as well.

**Comment by federicocappelli** [comment]
The crash was for the infinite loop (bad access), I have changed many things in my project, sorry can't replicate ;)

**Comment by matteogobbi** [comment]
Ok but was something in your code as here there is no any loop.
Moreover this component has even been used from others (in busuu as well).

Anyway, you are using it. ;)

Cheers!

On Tuesday, 24 March 2015, Federico Cappelli notifications@github.com
wrote:

> The crash was for the infinite loop (bad access), I have changed many
> things in my project, sorry can't replicate ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matteogobbi/MGTextView/issues/1#issuecomment-85619407
> .

## 

_Matteo Gobbi_
*Software iOS Engineer *
